/var/spool/slurmd/job4413663/slurm_script: line 13: conda: command not found
r22
Thu Jun 27 00:46:21 PDT 2024
Date and time: 2024-06-27 00:46:24.473735
len_slice  n_select_slc  beams  n_optimization_restarts  output_file
3 2 1 10 best_slices_test.txt
Redshifts:  [0.  0.2 0.5 1.  2.  3. ]
Computing loss function for slice 0
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:137: RuntimeWarning:overflow encountered in square
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:138: RuntimeWarning:invalid value encountered in add
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:137: RuntimeWarning:overflow encountered in square
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:138: RuntimeWarning:invalid value encountered in add
Time now: 2024-06-27 00:46:31.525776
Loss function for slice 0 = 0.05914205996246664
Computing loss function for slice 1
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:243: RuntimeWarning:invalid value encountered in true_divide
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:137: RuntimeWarning:overflow encountered in square
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:138: RuntimeWarning:invalid value encountered in add
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:243: RuntimeWarning:invalid value encountered in true_divide
Time now: 2024-06-27 00:46:38.813055
Loss function for slice 1 = 0.04908602600357812
Computing loss function for slice 2
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:137: RuntimeWarning:overflow encountered in square
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:138: RuntimeWarning:invalid value encountered in add
Time now: 2024-06-27 00:46:46.094907
Loss function for slice 2 = 0.07850653118810494
Computing loss function for slice 3
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:137: RuntimeWarning:overflow encountered in square
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:138: RuntimeWarning:invalid value encountered in add
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:243: RuntimeWarning:invalid value encountered in true_divide
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:137: RuntimeWarning:overflow encountered in square
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:138: RuntimeWarning:invalid value encountered in add
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:137: RuntimeWarning:overflow encountered in square
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:138: RuntimeWarning:invalid value encountered in add
Time now: 2024-06-27 00:46:51.380695
Loss function for slice 3 = 0.04872626040865887
Computing loss function for slice 4
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:137: RuntimeWarning:overflow encountered in square
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:138: RuntimeWarning:invalid value encountered in add
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:137: RuntimeWarning:overflow encountered in square
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:138: RuntimeWarning:invalid value encountered in add
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:137: RuntimeWarning:overflow encountered in square
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:138: RuntimeWarning:invalid value encountered in add
Time now: 2024-06-27 00:46:57.399026
Loss function for slice 4 = 0.04848510422002949
Computing loss function for slice 5
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:137: RuntimeWarning:overflow encountered in square
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:138: RuntimeWarning:invalid value encountered in add
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:137: RuntimeWarning:overflow encountered in square
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:138: RuntimeWarning:invalid value encountered in add
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:137: RuntimeWarning:overflow encountered in square
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:138: RuntimeWarning:invalid value encountered in add
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:243: RuntimeWarning:invalid value encountered in true_divide
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:137: RuntimeWarning:overflow encountered in square
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:138: RuntimeWarning:invalid value encountered in add
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:137: RuntimeWarning:overflow encountered in square
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:138: RuntimeWarning:invalid value encountered in add
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:137: RuntimeWarning:overflow encountered in square
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:138: RuntimeWarning:invalid value encountered in add
Time now: 2024-06-27 00:47:06.821213
Loss function for slice 5 = 0.05672780808956874
Computing loss function for slice 6
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:137: RuntimeWarning:overflow encountered in square
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:138: RuntimeWarning:invalid value encountered in add
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:243: RuntimeWarning:invalid value encountered in true_divide
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:137: RuntimeWarning:overflow encountered in square
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:138: RuntimeWarning:invalid value encountered in add
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:137: RuntimeWarning:overflow encountered in square
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:138: RuntimeWarning:invalid value encountered in add
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:137: RuntimeWarning:overflow encountered in square
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:138: RuntimeWarning:invalid value encountered in add
Time now: 2024-06-27 00:47:14.037284
Loss function for slice 6 = 0.03821898151335236
Computing loss function for slice 7
Time now: 2024-06-27 00:47:20.302466
Loss function for slice 7 = 0.10222338243539465
Computing loss function for slice 8
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:137: RuntimeWarning:overflow encountered in square
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:138: RuntimeWarning:invalid value encountered in add
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:137: RuntimeWarning:overflow encountered in square
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:138: RuntimeWarning:invalid value encountered in add
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:137: RuntimeWarning:overflow encountered in square
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:138: RuntimeWarning:invalid value encountered in add
Time now: 2024-06-27 00:47:27.143465
Loss function for slice 8 = 0.09074887234665059
Computing loss function for slice 9
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:137: RuntimeWarning:overflow encountered in square
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:138: RuntimeWarning:invalid value encountered in add
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:137: RuntimeWarning:overflow encountered in square
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:138: RuntimeWarning:invalid value encountered in add
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:137: RuntimeWarning:overflow encountered in square
 /rhome/yyang440/bigdata/anaconda3/envs/gpy-env/lib/python3.8/site-packages/GPy/kern/src/stationary.py:138: RuntimeWarning:invalid value encountered in add
